# Generated by Django 6.0 on 2026-01-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='mother_occupation',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
