# Generated by Django 6.0 on 2026-01-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='vh20hwGnVAYVhxZSIiD7VuIQ7Yf1B4kh', editable=False, max_length=32, unique=True),
        ),
    ]
